


dict_one = {
  'root/root/rsm:HouseWaybill (attribute_name)-xmlns:ram': 'iata:datamodel:3',
  'root/root/rsm:HouseWaybill (attribute_name)-xmlns:rsm': 'iata:housewaybill:1',
  'root/root/rsm:HouseWaybill/rsm:MessageHeaderDocument/ram:ID': '3e756a95-e6b2-4632-8254-3f9cf04057ce',
  'root/root/rsm:HouseWaybill/rsm:MessageHeaderDocument/ram:Name': 'House waybill',
  'root/root/rsm:HouseWaybill/rsm:MessageHeaderDocument/ram:TypeCode (attribute_name)-listID': '1001',
  'root/root/rsm:HouseWaybill/rsm:MessageHeaderDocument/ram:TypeCode (attribute_name)-listVersionID': 'D09A',
  'root/root/rsm:HouseWaybill/rsm:MessageHeaderDocument/ram:TypeCode': '703',
  'root/root/rsm:HouseWaybill/rsm:MessageHeaderDocument/ram:IssueDateTime': '2022-11-11T10:32:35',
  'root/root/rsm:HouseWaybill/rsm:MessageHeaderDocument/ram:PurposeCode': 'Creation',
  'root/root/rsm:HouseWaybill/rsm:MessageHeaderDocument/ram:VersionID': '3.00',
  'root/root/rsm:HouseWaybill/rsm:MessageHeaderDocument/ram:ConversationID': '69184383-297c-4e44-ba34-db37a3c63f26',
  'root/root/rsm:HouseWaybill/rsm:MessageHeaderDocument/ram:SenderParty/ram:PrimaryID (attribute_name)-schemeID': 'P',
  'root/root/rsm:HouseWaybill/rsm:MessageHeaderDocument/ram:SenderParty/ram:PrimaryID': 'CSGAIR01DXBFMEK',
  'root/root/rsm:HouseWaybill/rsm:MessageHeaderDocument/ram:RecipientParty/ram:PrimaryID (attribute_name)-schemeID': 'P',
  'root/root/rsm:HouseWaybill/rsm:MessageHeaderDocument/ram:RecipientParty/ram:PrimaryID': 'CSGCUS86CUSGW',
  'root/root/rsm:HouseWaybill/rsm:BusinessHeaderDocument/ram:ID': 'SIN1702',
  'root/root/rsm:HouseWaybill/rsm:BusinessHeaderDocument/ram:SignatoryConsignorAuthentication/ram:Signatory': 'XXX',
  'root/root/rsm:HouseWaybill/rsm:BusinessHeaderDocument/ram:SignatoryCarrierAuthentication/ram:ActualDateTime': '2002-07-01T05:10:10',
  'root/root/rsm:HouseWaybill/rsm:BusinessHeaderDocument/ram:SignatoryCarrierAuthentication/ram:Signatory': 'XXX',
  'root/root/rsm:HouseWaybill/rsm:BusinessHeaderDocument/ram:SignatoryCarrierAuthentication/ram:IssueAuthenticationLocation/ram:Name': 'XXX',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedTareGrossWeightMeasure (attribute_name)-unitCode': 'KGM',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedTareGrossWeightMeasure': '23',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:TotalPieceQuantity': '5',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:TransportContractDocument/ram:ID': '176-01112228',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:OriginLocation/ram:ID': 'SIN',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:FinalDestinationLocation/ram:ID': 'DAC',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:NilCarriageValueIndicator': 'true',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:NilCustomsValueIndicator': 'true',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:DeclaredValueForCustomsAmount (attribute_name)-currencyID': 'TWD',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:DeclaredValueForCustomsAmount': '0',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:NilInsuranceValueIndicator': 'true',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:InsuranceValueAmount (attribute_name)-currencyID': 'TWD',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:InsuranceValueAmount': '0',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:TotalChargePrepaidIndicator': 'true',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:TotalDisbursementPrepaidIndicator': 'true',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:IncludedTareGrossWeightMeasure (attribute_name)-unitCode': 'KGM',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:IncludedTareGrossWeightMeasure': '0.60',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:TotalPieceQuantity': '2',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:SummaryDescription': 'H1M1',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:ConsignorParty/ram:Name': 'NANJOMG INDUSTRIAL CO LTD',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:ConsignorParty/ram:PostalStructuredAddress/ram:PostcodeCode': '243',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:ConsignorParty/ram:PostalStructuredAddress/ram:StreetName': 'NO102 SHOU SHAN ROAD',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:ConsignorParty/ram:PostalStructuredAddress/ram:CityName': 'NEW TAIPEI',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:ConsignorParty/ram:PostalStructuredAddress/ram:CountryID (attribute_name)-schemeVersionID': 'second edition 2006',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:ConsignorParty/ram:PostalStructuredAddress/ram:CountryID': 'TW',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:ConsignorParty/ram:DefinedTradeContact/ram:DirectTelephoneCommunication/ram:CompleteNumber': '000000',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:ConsigneeParty/ram:Name': 'PT ASTRA OTOPARTS TBK',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:ConsigneeParty/ram:PostalStructuredAddress/ram:PostcodeCode': '14250',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:ConsigneeParty/ram:PostalStructuredAddress/ram:StreetName': 'JL PEGANGSAAN DUA KM 2 2 PEGANGSAAN',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:ConsigneeParty/ram:PostalStructuredAddress/ram:CityName': 'NEW YORK',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:ConsigneeParty/ram:PostalStructuredAddress/ram:CountryID (attribute_name)-schemeVersionID': 'second edition 2006',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:ConsigneeParty/ram:PostalStructuredAddress/ram:CountryID': 'US',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:ConsigneeParty/ram:DefinedTradeContact/ram:DirectTelephoneCommunication/ram:CompleteNumber': '00000',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:AssociatedParty/ram:Name': 'PT ASTRA OTOPARTS TBK',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:AssociatedParty/ram:RoleCode (attribute_name)-listID': '3035',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:AssociatedParty/ram:RoleCode (attribute_name)-listVersionID': 'D09A',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:AssociatedParty/ram:RoleCode': 'NI',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:AssociatedParty/ram:PostalStructuredAddress/ram:PostcodeCode': '14250',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:AssociatedParty/ram:PostalStructuredAddress/ram:StreetName': 'JL PEGANGSAAN DUA KM 2 2 PEGANGSAAN',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:AssociatedParty/ram:PostalStructuredAddress/ram:CityName': 'NEW YORK',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:AssociatedParty/ram:PostalStructuredAddress/ram:CountryID (attribute_name)-schemeVersionID': 'second edition 2006',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:AssociatedParty/ram:PostalStructuredAddress/ram:CountryID': 'US',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:AssociatedParty/ram:DefinedTradeContact/ram:DirectTelephoneCommunication/ram:CompleteNumber': '00000',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:OriginLocation/ram:ID': 'SIN',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:FinalDestinationLocation/ram:ID': 'DAC',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:HandlingSPHInstructions/ram:DescriptionCode': 'XXX',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:ApplicableOriginCurrencyExchange/ram:SourceCurrencyCode (attribute_name)-listID': 'ISO 4217 3A',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:ApplicableOriginCurrencyExchange/ram:SourceCurrencyCode (attribute_name)-listVersionID': '2007-06-18',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:ApplicableOriginCurrencyExchange/ram:SourceCurrencyCode': 'TWD',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:IncludedHouseConsignmentItem/ram:SequenceNumeric': '1',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:IncludedHouseConsignmentItem/ram:GrossWeightMeasure (attribute_name)-unitCode': 'KGM',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:IncludedHouseConsignmentItem/ram:GrossWeightMeasure': '0.60',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:IncludedHouseConsignmentItem/ram:PieceQuantity': '2',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:IncludedHouseConsignmentItem/ram:Information': 'NDA',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:IncludedHouseConsignmentItem/ram:NatureIdentificationTransportCargo/ram:Identification': 'H1M1',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:IncludedHouseConsignmentItem/ram:TransportLogisticsPackage/ram:ItemQuantity': '2',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:IncludedHouseConsignmentItem/ram:TransportLogisticsPackage/ram:GrossWeightMeasure (attribute_name)-unitCode': 'KGM',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:IncludedHouseConsignmentItem/ram:TransportLogisticsPackage/ram:GrossWeightMeasure': '0.60',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:IncludedHouseConsignmentItem/ram:ApplicableFreightRateServiceCharge/ram:ChargeableWeightMeasure (attribute_name)-unitCode': 'KGM',
  'root/root/rsm:HouseWaybill/rsm:MasterConsignment/ram:IncludedHouseConsignment/ram:IncludedHouseConsignmentItem/ram:ApplicableFreightRateServiceCharge/ram:ChargeableWeightMeasure': '0.60'
}

text_to_add_one = {}

dict_two = {
  'root/root/rsm:FlightManifest (attribute_name)-xmlns:ram': 'iata:datamodel:3',
  'root/root/rsm:FlightManifest (attribute_name)-xmlns:rsm': 'iata:flightmanifest:1',
  'root/root/rsm:FlightManifest/rsm:MessageHeaderDocument/ram:ID': 'EK011111NOV2022',
  'root/root/rsm:FlightManifest/rsm:MessageHeaderDocument/ram:Name': 'Transport Loading Report',
  'root/root/rsm:FlightManifest/rsm:MessageHeaderDocument/ram:TypeCode (attribute_name)-listID': '1001',
  'root/root/rsm:FlightManifest/rsm:MessageHeaderDocument/ram:TypeCode (attribute_name)-listVersionID': 'D09A',
  'root/root/rsm:FlightManifest/rsm:MessageHeaderDocument/ram:TypeCode': '122',
  'root/root/rsm:FlightManifest/rsm:MessageHeaderDocument/ram:IssueDateTime': '2022-11-11T10:32:16',
  'root/root/rsm:FlightManifest/rsm:MessageHeaderDocument/ram:PurposeCode': 'Creation',
  'root/root/rsm:FlightManifest/rsm:MessageHeaderDocument/ram:VersionID': '2.0',
  'root/root/rsm:FlightManifest/rsm:MessageHeaderDocument/ram:ConversationID': 'df9d2e2e-b854-468c-a484-ad705c73f5ef',
  'root/root/rsm:FlightManifest/rsm:MessageHeaderDocument/ram:SenderParty/ram:PrimaryID (attribute_name)-schemeID': 'P',
  'root/root/rsm:FlightManifest/rsm:MessageHeaderDocument/ram:SenderParty/ram:PrimaryID': 'CSGAIR01DXBFMEK',
  'root/root/rsm:FlightManifest/rsm:MessageHeaderDocument/ram:RecipientParty/ram:PrimaryID (attribute_name)-schemeID': 'P',
  'root/root/rsm:FlightManifest/rsm:MessageHeaderDocument/ram:RecipientParty/ram:PrimaryID': 'CSGCUS86CUSGW',
  'root/root/rsm:FlightManifest/rsm:BusinessHeaderDocument/ram:ID': 'EK011111NOV2022',
  'root/root/rsm:FlightManifest/rsm:LogisticsTransportMovement/ram:StageCode': 'EK0111',
  'root/root/rsm:FlightManifest/rsm:LogisticsTransportMovement/ram:ModeCode (attribute_name)-listID': 'Recommendation 19',
  'root/root/rsm:FlightManifest/rsm:LogisticsTransportMovement/ram:ModeCode (attribute_name)-listVersionID': '2',
  'root/root/rsm:FlightManifest/rsm:LogisticsTransportMovement/ram:ModeCode': '4',
  'root/root/rsm:FlightManifest/rsm:LogisticsTransportMovement/ram:ID': 'EK0111',
  'root/root/rsm:FlightManifest/rsm:LogisticsTransportMovement/ram:SequenceNumeric': '1',
  'root/root/rsm:FlightManifest/rsm:LogisticsTransportMovement/ram:UsedLogisticsTransportMeans/ram:Name': 'BD',
  'root/root/rsm:FlightManifest/rsm:LogisticsTransportMovement/ram:DepartureEvent/ram:DepartureOccurrenceDateTime': '2022-11-11T01:30:00',
  'root/root/rsm:FlightManifest/rsm:LogisticsTransportMovement/ram:DepartureEvent/ram:DepartureDateTimeTypeCode': 'S',
  'root/root/rsm:FlightManifest/rsm:LogisticsTransportMovement/ram:DepartureEvent/ram:OccurrenceDepartureLocation/ram:ID': 'SIN',
  'root/root/rsm:FlightManifest/rsm:LogisticsTransportMovement/ram:DepartureEvent/ram:OccurrenceDepartureLocation/ram:TypeCode': 'Airport',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:ArrivalOccurrenceDateTime': '2022-11-11T06:30:00',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:ArrivalDateTimeTypeCode': 'S',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:DepartureOccurrenceDateTime': '2022-11-11T01:30:00',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:DepartureDateTimeTypeCode': 'S',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:OccurrenceArrivalLocation/ram:ID': 'DAC',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:OccurrenceArrivalLocation/ram:TypeCode': 'Airport',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:TypeCode': 'BLK',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment/ram:GrossWeightMeasure (attribute_name)-unitCode': 'KGM',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment/ram:GrossWeightMeasure': '24',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment/ram:GrossVolumeMeasure (attribute_name)-unitCode': 'MTQ',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment/ram:GrossVolumeMeasure': '32',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment/ram:TotalPieceQuantity': '5',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment/ram:SummaryDescription': 'M1',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment/ram:TransportSplitDescription': 'P',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment/ram:TransportContractDocument/ram:ID': '176-01112228',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment/ram:OriginLocation/ram:ID': 'SIN',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment/ram:FinalDestinationLocation/ram:ID': 'DAC',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment__duplicate__/ram:GrossWeightMeasure (attribute_name)-unitCode': 'KGM',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment__duplicate__/ram:GrossWeightMeasure': '24',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment__duplicate__/ram:GrossVolumeMeasure (attribute_name)-unitCode': 'MTQ',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment__duplicate__/ram:GrossVolumeMeasure': '32',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment__duplicate__/ram:TotalPieceQuantity': '5',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment__duplicate__/ram:SummaryDescription': 'M3',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment__duplicate__/ram:TransportSplitDescription': 'T',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment__duplicate__/ram:TransportContractDocument/ram:ID': '176-01112223',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment__duplicate__/ram:OriginLocation/ram:ID': 'SIN',
  'root/root/rsm:FlightManifest/rsm:ArrivalEvent/ram:AssociatedTransportCargo/ram:IncludedMasterConsignment__duplicate__/ram:FinalDestinationLocation/ram:ID': 'DAC'
}

text_to_add_two = {}

dict_three = {
  'root/root/check/MessageHeaderDocument/ram:ID': 'f17ec2f9-a67d-4785-9a42-272edc272269',
  'root/root/check/MessageHeaderDocument/ram:Name': 'Air Waybill',
  'root/root/check/MessageHeaderDocument/ram:TypeCode (attribute_name)-listID': '1001',
  'root/root/check/MessageHeaderDocument/ram:TypeCode (attribute_name)-listVersionID': 'D09A',
  'root/root/check/MessageHeaderDocument/ram:TypeCode': '741',
  'root/root/check/MessageHeaderDocument/ram:IssueDateTime': '2022-11-11T10:32:30',
  'root/root/check/MessageHeaderDocument/ram:PurposeCode': 'Creation',
  'root/root/check/MessageHeaderDocument/ram:VersionID': '3',
  'root/root/check/MessageHeaderDocument/ram:ConversationID': 'dbb22bf1-840a-47e2-9409-51b620c20973',
  'root/root/check/MessageHeaderDocument/ram:SenderParty/ram:PrimaryID (attribute_name)-schemeID': 'P',
  'root/root/check/MessageHeaderDocument/ram:SenderParty/ram:PrimaryID': 'CSGAIR01DXBFMEK',
  'root/root/check/MessageHeaderDocument/ram:RecipientParty/ram:PrimaryID (attribute_name)-schemeID': 'P',
  'root/root/check/MessageHeaderDocument/ram:RecipientParty/ram:PrimaryID': 'CSGCUS86CUSGW',
  'root/root/check/BusinessHeaderDocument/ram:ID': '176-01112228',
  'root/root/check/BusinessHeaderDocument/ram:SignatoryCarrierAuthentication/ram:ActualDateTime': '2021-12-10T00:00:00',
  'root/root/check/BusinessHeaderDocument/ram:SignatoryCarrierAuthentication/ram:Signatory': 'DHL EXPRESS',
  'root/root/check/BusinessHeaderDocument/ram:SignatoryCarrierAuthentication/ram:IssueAuthenticationLocation/ram:Name': 'SINGAPORE',
  'root/root/check/MasterConsignment/ram:NilCarriageValueIndicator': 'true',
  'root/root/check/MasterConsignment/ram:NilCustomsValueIndicator': 'true',
  'root/root/check/MasterConsignment/ram:DeclaredValueForCustomsAmount (attribute_name)-currencyID': 'TWD',
  'root/root/check/MasterConsignment/ram:DeclaredValueForCustomsAmount': '0',
  'root/root/check/MasterConsignment/ram:NilInsuranceValueIndicator': 'true',
  'root/root/check/MasterConsignment/ram:InsuranceValueAmount (attribute_name)-currencyID': 'TWD',
  'root/root/check/MasterConsignment/ram:InsuranceValueAmount': '0',
  'root/root/check/MasterConsignment/ram:TotalChargePrepaidIndicator': 'true',
  'root/root/check/MasterConsignment/ram:TotalDisbursementPrepaidIndicator': 'true',
  'root/root/check/MasterConsignment/ram:IncludedTareGrossWeightMeasure (attribute_name)-unitCode': 'KGM',
  'root/root/check/MasterConsignment/ram:IncludedTareGrossWeightMeasure': '24',
  'root/root/check/MasterConsignment/ram:GrossVolumeMeasure (attribute_name)-unitCode': 'MTQ',
  'root/root/check/MasterConsignment/ram:GrossVolumeMeasure': '32',
  'root/root/check/MasterConsignment/ram:TotalPieceQuantity': '5',
  'root/root/check/MasterConsignment/ram:ConsignorParty/ram:Name': 'SENSESOFT 002',
  'root/root/check/MasterConsignment/ram:ConsignorParty/ram:PostalStructuredAddress/ram:StreetName': '1 BDOTTS RD.',
  'root/root/check/MasterConsignment/ram:ConsignorParty/ram:PostalStructuredAddress/ram:CityName': 'SINGAPORE',
  'root/root/check/MasterConsignment/ram:ConsignorParty/ram:PostalStructuredAddress/ram:CountryID (attribute_name)-schemeVersionID': 'second edition 2006',
  'root/root/check/MasterConsignment/ram:ConsignorParty/ram:PostalStructuredAddress/ram:CountryID': 'SG',
  'root/root/check/MasterConsignment/ram:ConsigneeParty/ram:Name': 'DHL EXPRESS',
  'root/root/check/MasterConsignment/ram:ConsigneeParty/ram:PostalStructuredAddress/ram:StreetName': '123 ST. LAGOS',
  'root/root/check/MasterConsignment/ram:ConsigneeParty/ram:PostalStructuredAddress/ram:CityName': 'BANGLADESH',
  'root/root/check/MasterConsignment/ram:ConsigneeParty/ram:PostalStructuredAddress/ram:CountryID (attribute_name)-schemeVersionID': 'second edition 2006',
  'root/root/check/MasterConsignment/ram:ConsigneeParty/ram:PostalStructuredAddress/ram:CountryID': 'BR',
  'root/root/check/MasterConsignment/ram:FreightForwarderParty/ram:Name': 'DHL EXPRESS',
  'root/root/check/MasterConsignment/ram:FreightForwarderParty/ram:CargoAgentID': '1234567',
  'root/root/check/MasterConsignment/ram:FreightForwarderParty/ram:FreightForwarderAddress/ram:CityName': 'SINGAPORE',
  'root/root/check/MasterConsignment/ram:AssociatedParty/ram:Name': 'DHL EXPRESS',
  'root/root/check/MasterConsignment/ram:AssociatedParty/ram:RoleCode (attribute_name)-listID': '3035',
  'root/root/check/MasterConsignment/ram:AssociatedParty/ram:RoleCode (attribute_name)-listVersionID': 'D09A',
  'root/root/check/MasterConsignment/ram:AssociatedParty/ram:RoleCode': 'NI',
  'root/root/check/MasterConsignment/ram:AssociatedParty/ram:PostalStructuredAddress/ram:StreetName': '123 ST. LAGOS',
  'root/root/check/MasterConsignment/ram:AssociatedParty/ram:PostalStructuredAddress/ram:CityName': 'BANGLADESH',
  'root/root/check/MasterConsignment/ram:AssociatedParty/ram:PostalStructuredAddress/ram:CountryID (attribute_name)-schemeVersionID': 'second edition 2006',
  'root/root/check/MasterConsignment/ram:AssociatedParty/ram:PostalStructuredAddress/ram:CountryID': 'BR',
  'root/root/check/MasterConsignment/ram:OriginLocation/ram:ID': 'SIN',
  'root/root/check/MasterConsignment/ram:FinalDestinationLocation/ram:ID': 'DAC',
  'root/root/check/MasterConsignment/ram:SpecifiedLogisticsTransportMovement/ram:ID': 'EK0111',
  'root/root/check/MasterConsignment/ram:SpecifiedLogisticsTransportMovement/ram:UsedLogisticsTransportMeans/ram:Name': 'EK',
  'root/root/check/MasterConsignment/ram:SpecifiedLogisticsTransportMovement/ram:ArrivalEvent/ram:ScheduledOccurrenceDateTime': '2021-12-05T00:00:00',
  'root/root/check/MasterConsignment/ram:SpecifiedLogisticsTransportMovement/ram:ArrivalEvent/ram:OccurrenceArrivalLocation/ram:ID': 'BKK',
  'root/root/check/MasterConsignment/ram:SpecifiedLogisticsTransportMovement/ram:ArrivalEvent/ram:OccurrenceArrivalLocation/ram:Name': 'QR',
  'root/root/check/MasterConsignment/ram:SpecifiedLogisticsTransportMovement/ram:DepartureEvent/ram:ScheduledOccurrenceDateTime': '2021-12-05T00:00:00',
  'root/root/check/MasterConsignment/ram:ApplicableOriginCurrencyExchange/ram:SourceCurrencyCode (attribute_name)-listID': 'ISO 4217 3A',
  'root/root/check/MasterConsignment/ram:ApplicableOriginCurrencyExchange/ram:SourceCurrencyCode (attribute_name)-listVersionID': '2007-06-18',
  'root/root/check/MasterConsignment/ram:ApplicableOriginCurrencyExchange/ram:SourceCurrencyCode': 'SGD',
  'root/root/check/MasterConsignment/ram:ApplicableRating/ram:TypeCode': 'F',
  'root/root/check/MasterConsignment/ram:ApplicableRating/ram:IncludedMasterConsignmentItem/ram:SequenceNumeric': '1',
  'root/root/check/MasterConsignment/ram:ApplicableRating/ram:IncludedMasterConsignmentItem/ram:GrossWeightMeasure (attribute_name)-unitCode': 'KGM',
  'root/root/check/MasterConsignment/ram:ApplicableRating/ram:IncludedMasterConsignmentItem/ram:GrossWeightMeasure': '5',
  'root/root/check/MasterConsignment/ram:ApplicableRating/ram:IncludedMasterConsignmentItem/ram:PieceQuantity': '1',
  'root/root/check/MasterConsignment/ram:ApplicableRating/ram:IncludedMasterConsignmentItem/ram:NatureIdentificationTransportCargo/ram:Identification': 'CONSOLLAPTOPS 12345 90416274 DELIVERY',
  'root/root/check/MasterConsignment/ram:ApplicableRating/ram:IncludedMasterConsignmentItem/ram:ApplicableFreightRateServiceCharge/ram:CategoryCode': 'M',
  'root/root/check/MasterConsignment/ram:ApplicableRating/ram:IncludedMasterConsignmentItem/ram:ApplicableFreightRateServiceCharge/ram:ChargeableWeightMeasure (attribute_name)-unitCode': 'KGM',
  'root/root/check/MasterConsignment/ram:ApplicableRating/ram:IncludedMasterConsignmentItem/ram:ApplicableFreightRateServiceCharge/ram:ChargeableWeightMeasure': '3.523',
  'root/root/check/MasterConsignment/ram:ApplicableRating/ram:IncludedMasterConsignmentItem/ram:ApplicableFreightRateServiceCharge/ram:AppliedRate': '5',
  'root/root/check/MasterConsignment/ram:ApplicableRating/ram:IncludedMasterConsignmentItem/ram:ApplicableFreightRateServiceCharge/ram:AppliedAmount (attribute_name)-currencyID': 'SGD',
  'root/root/check/MasterConsignment/ram:ApplicableRating/ram:IncludedMasterConsignmentItem/ram:ApplicableFreightRateServiceCharge/ram:AppliedAmount': '5',
  'root/root/check/MasterConsignment/ram:ApplicableRating/ram:IncludedMasterConsignmentItem__duplicate__/ram:SequenceNumeric': '2',
  'root/root/check/MasterConsignment/ram:ApplicableRating/ram:IncludedMasterConsignmentItem__duplicate__/ram:Information': 'NDA',
  'root/root/check/MasterConsignment/ram:ApplicableTotalRating/ram:TypeCode': 'F',
  'root/root/check/MasterConsignment/ram:ApplicableTotalRating/ram:ApplicablePrepaidCollectMonetarySummation/ram:PrepaidIndicator': 'true',
  'root/root/check/MasterConsignment/ram:ApplicableTotalRating/ram:ApplicablePrepaidCollectMonetarySummation/ram:WeightChargeTotalAmount (attribute_name)-currencyID': 'SGD',
  'root/root/check/MasterConsignment/ram:ApplicableTotalRating/ram:ApplicablePrepaidCollectMonetarySummation/ram:WeightChargeTotalAmount': '800',
  'root/root/check/MasterConsignment/ram:ApplicableTotalRating/ram:ApplicablePrepaidCollectMonetarySummation/ram:GrandTotalAmount (attribute_name)-currencyID': 'SGD',
  'root/root/check/MasterConsignment/ram:ApplicableTotalRating/ram:ApplicablePrepaidCollectMonetarySummation/ram:GrandTotalAmount': '800'
}

text_to_add_three = {}